# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8eb711eb98476b859f0d403a5c5768c0e06395c8145d4f1e7d1562dba9d882624fe5bbf1c2d95848b41a98604185d8ab221bf4788aa23ba099b6bb71bdeacc11

test:
  secret_key_base: 1dd32100f2f42f3f6a668057519643cc4b92a902115fd29b895148b9443f348c47b6d5b9ddaaf8bd0c2367c6adda9b99115049dcb761e2619c35e1a53fb716a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
